# Generated by Django 4.2.13 on 2024-06-15 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("imagegen", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="image",
            name="image",
        ),
        migrations.AddField(
            model_name="image",
            name="category",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="image",
            name="channel",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="image",
            name="product",
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
