# Generated by Django 4.2.13 on 2024-06-15 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("imagegen", "0002_remove_image_image_image_category_image_channel_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="image",
            name="image",
            field=models.TextField(default=""),
            preserve_default=False,
        ),
    ]
