# Generated by Django 4.2.13 on 2024-06-16 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("imagegen", "0003_image_image"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="image",
            name="category",
        ),
        migrations.AddField(
            model_name="image",
            name="age",
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name="image",
            name="app_vehicle_ind",
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name="image",
            name="cnt_tr_all_3m",
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name="image",
            name="cnt_tr_buy_3m",
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name="image",
            name="cnt_tr_cash_3m",
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name="image",
            name="cnt_tr_mobile_3m",
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name="image",
            name="cnt_tr_oil_3m",
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name="image",
            name="cnt_tr_on_card_3m",
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name="image",
            name="cnt_tr_service_3m",
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name="image",
            name="cnt_tr_top_up_3m",
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name="image",
            name="gender",
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name="image",
            name="sum_zp_12m",
            field=models.FloatField(null=True),
        ),
    ]
