# Generated by Django 4.2.13 on 2024-06-16 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("imagegen", "0004_remove_image_category_image_age_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="image",
            name="age",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="image",
            name="app_vehicle_ind",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="image",
            name="cnt_tr_all_3m",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="image",
            name="cnt_tr_buy_3m",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="image",
            name="cnt_tr_cash_3m",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="image",
            name="cnt_tr_mobile_3m",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="image",
            name="cnt_tr_oil_3m",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="image",
            name="cnt_tr_on_card_3m",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="image",
            name="cnt_tr_service_3m",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="image",
            name="cnt_tr_top_up_3m",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="image",
            name="gender",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="image",
            name="sum_zp_12m",
            field=models.FloatField(blank=True, null=True),
        ),
    ]
